GET http://localhost:5257/api/users/1/exercises

###
GET http://localhost:5257/api/users/4/exercises/6


###
POST http://localhost:5257/api/users/1/exercises
Content-Type: application/json

{
    "userId": 1,
    "name": "Super squat"
}

###
POST http://localhost:5257/api/users/1/exercises
Content-Type: application/json

{
    "userId": 1,
    "name": "Press ups"
}


###
PUT http://localhost:5257/api/users/4/exercises/11
Content-Type: application/json

{
    "userId": 4,
    "name": "New thing"
}

###
DELETE http://localhost:5257/api/users/4/exercises/10
