# fly.toml app configuration file generated for workout-api-thrumming-grass-6189 on 2024-09-02T12:06:52+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'workout-api-thrumming-grass-6189'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
