GET http://localhost:5257/api/users

###
GET http://localhost:5257/api/users/7

###
POST http://localhost:5257/api/users
Content-Type: application/json

{
    "name": "John Smith",
    "email": "test@email.com"
}

###
POST http://localhost:5257/api/users
Content-Type: application/json

{
    "name": "Jackie Brown",
    "email": "test@yahoo.com"
}


###
PUT http://localhost:5257/api/users/2
Content-Type: application/json

{
    "name": "Jack Sparrow",
    "email": "test@email.com"
}

###
DELETE http://localhost:5257/api/users/5

###
POST http://localhost:5257/api/login
Content-Type: application/json

{
    "email": "test@email.com",
    "password": ""
}