// // <auto-generated />
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Migrations;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// using Workout.Api.Data;

// #nullable disable

// namespace Workout.Api.Migrations
// {
//     [DbContext(typeof(WorkoutContext))]
//     [Migration("20240816074424_InitialCreate")]
//     partial class InitialCreate
//     {
//         /// <inheritdoc />
//         protected override void BuildTargetModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

//             modelBuilder.Entity("Workout.Api.Entities.Exercise", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("TEXT NOT NULL");

//                     b.Property<int>("UserId")
//                         .HasColumnType("INTEGER");

//                     b.HasKey("Id");

//                     b.HasIndex("UserId");

//                     b.ToTable("Exercises");
//                 });

//             modelBuilder.Entity("Workout.Api.Entities.Routine", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("TEXT NOT NULL");

//                     b.Property<int>("UserId")
//                         .HasColumnType("INTEGER");

//                     b.HasKey("Id");

//                     b.HasIndex("UserId");

//                     b.ToTable("Routines");
//                 });

//             modelBuilder.Entity("Workout.Api.Entities.RoutineExercise", b =>
//                 {
//                     b.Property<int>("RoutineId")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("ExerciseId")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("ExerciseOrder")
//                         .HasColumnType("INTEGER");

//                     b.Property<int>("Id")
//                         .HasColumnType("INTEGER");

//                     b.HasKey("RoutineId", "ExerciseId");

//                     b.HasIndex("ExerciseId");

//                     b.ToTable("RoutineExercise");
//                 });

//             modelBuilder.Entity("Workout.Api.Entities.User", b =>
//                 {
//                     b.Property<int>("Id")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("INTEGER");

//                     b.Property<string>("Email")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasColumnType("TEXT");

//                     b.HasKey("Id");

//                     b.ToTable("Users");
//                 });

//             modelBuilder.Entity("Workout.Api.Entities.Exercise", b =>
//                 {
//                     b.HasOne("Workout.Api.Entities.User", "User")
//                         .WithMany("Exercises")
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("User");
//                 });

//             modelBuilder.Entity("Workout.Api.Entities.Routine", b =>
//                 {
//                     b.HasOne("Workout.Api.Entities.User", "User")
//                         .WithMany("Routines")
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("User");
//                 });

//             modelBuilder.Entity("Workout.Api.Entities.RoutineExercise", b =>
//                 {
//                     b.HasOne("Workout.Api.Entities.Exercise", "Exercise")
//                         .WithMany("RoutineExercises")
//                         .HasForeignKey("ExerciseId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("Workout.Api.Entities.Routine", "Routine")
//                         .WithMany("RoutineExercises")
//                         .HasForeignKey("RoutineId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Exercise");

//                     b.Navigation("Routine");
//                 });

//             modelBuilder.Entity("Workout.Api.Entities.Exercise", b =>
//                 {
//                     b.Navigation("RoutineExercises");
//                 });

//             modelBuilder.Entity("Workout.Api.Entities.Routine", b =>
//                 {
//                     b.Navigation("RoutineExercises");
//                 });

//             modelBuilder.Entity("Workout.Api.Entities.User", b =>
//                 {
//                     b.Navigation("Exercises");

//                     b.Navigation("Routines");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
