# fly.toml app configuration file generated for flyio-mysql-wild-bush-4200 on 2024-09-03T11:06:18+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flyio-mysql-wild-bush-4200'
primary_region = 'syd'

[build]
  image = 'mysql:8.0.39'

[env]
  MYSQL_DATABASE = 'workout'
  MYSQL_USER = 'non_root_user'

[processes]
  app = '--datadir /data/mysql --default-authentication-plugin mysql_native_password'

[[mounts]]
  source = 'mysqldata'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
