# fly.toml app configuration file generated for mysql-db-workout-app on 2024-09-05T17:33:03+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mysql-db-workout-app'
primary_region = 'syd'

[build]
image = 'mysql:8.0.39'


[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[processes]
app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password \
    --performance-schema=OFF"""

[mounts]
source = "mysqldata"
destination = "/data"

[env]
MYSQL_DATABASE = "workout"
MYSQL_USER = "root"
