name: Automated API tests using Newman CLI

on:
  push:
    branches:
      - test-branch
    paths:   
      - 'Workout.Api/**/*'

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Check API readiness
        run: |
          if ! curl -f -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN_DEV }}" "${{ vars.PROXY_LOCAL_SERVER }}/api/health"; then
            echo "API is not ready."
            exit 1  # Fail the job if the API is not ready
          fi

      - name: Install Newman
        run: npm install -g newman

      - name: Install reporters
        run: npm install -g newman-reporter-html  

      - name: Run Newman API tests
        run: |
          newman run postman/Workout_app.postman_collection.json \
          --env-var "access_token_dev=api-test-token" \
          --environment postman/Local_development.postman_environment.json \
          --global-var "base_url=https://***REMOVED***" \
          --reporters html \
          --reporter-html-export newman/newman-report.html \
          --verbose

      - name: Upload HTML Newman report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report-html
          path: newman/newman-report.html
