name: Automated API tests using Newman CLI

on:
  push:
    branches:
      - main
    paths:   
      - 'Workout.Api/**/*'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Check API readiness
        run: |
          if ! curl -f -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN_DEV }}" "${{ vars.PROXY_LOCAL_SERVER }}/api/health"; then
            echo "API is not ready."
            exit 1  # Fail the job if the API is not ready
          fi

      - name: Install Newman and Reporters
        run: |
          npm install -g newman
          npm install -g newman-reporter-html  

      - name: Run Newman API tests
        run: |
          echo "Running Newman tests..."
          newman run postman/Workout_app.postman_collection.json \
            --global-var "access_token_dev=${{ secrets.ACCESS_TOKEN_DEV }}" \
            --environment postman/Local_development.postman_environment.json \
            --env-var "base_url=${{ vars.PROXY_LOCAL_SERVER }}" \
            --reporters cli,html \
            --reporter-html-export newman/newman-report.html \
            --verbose > newman_output.log 2>&1 || {
              echo "Newman tests failed. Output:"
              cat newman_output.log
              exit 1
            }
          echo "Newman tests completed successfully."


      - name: Upload HTML Newman report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report-html
          path: newman/newman-report.html
