name: Automated API tests using Newman CLI

on:
  push:
    branches:
      - main
    paths:   
      - 'WorkoutApp.Api/**/*'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    environment: Development
    env:
      AUTH0_URL: ${{ vars.AUTH0_URL }}
      AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      API_TESTER_ADMIN1_USERNAME: ${{ vars.API_TESTER_ADMIN1_USERNAME }}
      API_TESTER_ADMIN1_PASSWORD: ${{ secrets.API_TESTER_ADMIN1_PASSWORD }}
      BASE_URL: ${{ vars.BASE_URL }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Newman and Reporters
        run: |
          npm install -g newman
          npm install -g newman-reporter-html  

      - name: Run Newman API tests
        run: |
          echo "Running Newman tests..."
          newman run postman/"Workout-app functional API tests.postman_collection.json" \
            --env-var "auth0_url=${AUTH0_URL}" \
            --env-var "auth0_audience=${AUTH0_AUDIENCE}" \
            --env-var "auth0_client_secret=${AUTH0_CLIENT_SECRET}" \
            --env-var "auth0_client_id=${AUTH0_CLIENT_ID}" \
            --env-var "api_tester_admin1_username=${API_TESTER_ADMIN1_USERNAME}" \
            --env-var "api_tester_admin1_password=${API_TESTER_ADMIN1_PASSWORD}" \
            --env-var "base_url=${BASE_URL}" \
            --reporters cli,html \
            --reporter-html-export newman/newman-report.html \
            --verbose > newman_output.log 2>&1 || {
              echo "Newman tests failed. Output:"
              cat newman_output.log
              exit 1
            }
          echo "Newman tests completed successfully."

      - name: Handle Newman HTML Report
        run: |
          if [[ "${GITHUB_ACTIONS}" == "true" ]]; then
            echo "Running in GitHub Actions, uploading artifact..."
            # Artifact upload is handled in the next step
          else
            echo "Running locally with act. Saving report to ./local-newman-reports/"
            mkdir -p ./local-newman-reports
            cp newman/newman-report.html ./local-newman-reports/
          fi

      - name: Upload HTML Newman report
        if: ${{ github.action }}
        uses: actions/upload-artifact@v4
        with:
          name: newman-report-html
          path: newman/newman-report.html
