name: Automated API tests using Newman CLI

on:
  push:
    branches:
      - main
    paths:   
      - 'Workout.Api/**/*'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN_DEV: ${{ secrets.ACCESS_TOKEN_DEV }}
      PROXY_LOCAL_SERVER: ${{ vars.PROXY_LOCAL_SERVER }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Check API readiness
        run: |
          if ! curl -f -H "Authorization: Bearer ${ACCESS_TOKEN_DEV}" "${PROXY_LOCAL_SERVER}/api/health"; then
            echo "API is not ready."
            exit 1  # Fail the job if the API is not ready
          fi

      - name: Install Newman and Reporters
        run: |
          npm install -g newman
          npm install -g newman-reporter-html  

      - name: Run Newman API tests
        run: |
          echo "Running Newman tests..."
          newman run postman/Workout_app.postman_collection.json \
            --global-var "access_token_dev=${ACCESS_TOKEN_DEV}" \
            --environment postman/Local_development.postman_environment.json \
            --env-var "base_url=${PROXY_LOCAL_SERVER}" \
            --reporters cli,html \
            --reporter-html-export newman/newman-report.html \
            --verbose > newman_output.log 2>&1 || {
              echo "Newman tests failed. Output:"
              cat newman_output.log
              exit 1
            }
          echo "Newman tests completed successfully."

      - name: Handle Newman HTML Report
        run: |
          if [[ "${GITHUB_ACTIONS}" == "true" ]]; then
            echo "Running in GitHub Actions, uploading artifact..."
            # Artifact upload is handled in the next step
          else
            echo "Running locally with act. Saving report to ./local-newman-reports/"
            mkdir -p ./local-newman-reports
            cp newman/newman-report.html ./local-newman-reports/
          fi

      - name: Upload HTML Newman report
        if: ${{ runner.env.GITHUB_ACTIONS == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: newman-report-html
          path: newman/newman-report.html
